# A sample Gemfile
source "https://rubygems.org"

gem "rspec"
gem "rake"
gem "simplecov"
gem "celluloid"
gem "celluloid-io"
gem "daemons"
gem "rack"
gem "mongrel", ">= 1.2.0.pre2"
gem "activesupport"
gem "activerecord"
gem "factory_girl"
gem "pg"
