# A sample Gemfile
source "https://rubygems.org"

gem "rspec"
gem "celluloid"
gem "daemons"
gem "rack"
gem "mongrel", ">= 1.2.0.pre2"
gem "activesupport"
gem "activerecord"
gem "mysql2"
gem "factory_girl"
gem "debugger"
gem "sqlite3"
